### GET: List airlines (/api/airlines)
GET http://localhost:5000/api/airlines HTTP/1.1


### GET: List by airline id (/api/airlines/{id})
GET http://localhost:5000/api/airlines/VN HTTP/1.1


### PUT: Update airline by id (/api/airlines/{id})
PUT http://localhost:5000/api/airlines/VN HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjMwIiwicm9sZSI6IlNUQUZGIiwibmJmIjoxNTc1OTQ4NzkwLCJleHAiOjE1NzY1NTM1OTAsImlhdCI6MTU3NTk0ODc5MH0.5SAMtF9jogQU9lP37NrqDpwMbTyIr803Gwxh13HOCvQ
Content-Type: application/json

{
  "id": "VN",
  "name": "Vietnam Airlines"
}


### POST: Create new airline (/api/airlines)
POST http://localhost:5000/api/airlines HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjMwIiwicm9sZSI6IlNUQUZGIiwibmJmIjoxNTc1OTQ4NzkwLCJleHAiOjE1NzY1NTM1OTAsImlhdCI6MTU3NTk0ODc5MH0.5SAMtF9jogQU9lP37NrqDpwMbTyIr803Gwxh13HOCvQ
Content-Type: application/json

{
  "id": "VA",
  "name": "Vietnam Airlines 123"
}


### DELETE: Remove airline by id (/api/airlines/{id})
DELETE http://localhost:5000/api/airlines/VA HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjMwIiwicm9sZSI6IlNUQUZGIiwibmJmIjoxNTc1OTQ4NzkwLCJleHAiOjE1NzY1NTM1OTAsImlhdCI6MTU3NTk0ODc5MH0.5SAMtF9jogQU9lP37NrqDpwMbTyIr803Gwxh13HOCvQ