### GET: List flights by date (/api/searchflights)
GET http://localhost:5000/api/searchflights?airportFrom=SGN&airportTo=HAN&departureDate=2019-12-13&returnDate=2019-12-15&ticketCategories[]={"id":1,"quantity":1}&ticketCategories[]={"id":2,"quantity":1}&ticketCategories[]={"id":3,"quantity":1} HTTP/1.1
Content-Type: application/json