### GET: List TicketCategories (/api/ticketcategories)
GET http://localhost:5000/api/ticketCategories


### GET: List by TicketCategory id (/api/ticketcategories/{id})
GET http://localhost:5000/api/ticketcategories/1


### PUT: Update TicketCategory by id (/api/ticketcategories/{id})
PUT http://localhost:5000/api/ticketcategories/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjMwIiwicm9sZSI6IlNUQUZGIiwibmJmIjoxNTc1OTQ4NzkwLCJleHAiOjE1NzY1NTM1OTAsImlhdCI6MTU3NTk0ODc5MH0.5SAMtF9jogQU9lP37NrqDpwMbTyIr803Gwxh13HOCvQ
Content-Type: application/json

{
  "name": "Người Lớn"
}


### POST: Create new TicketCategory (/api/ticketcategories)
POST http://localhost:5000/api/ticketcategories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjMwIiwicm9sZSI6IlNUQUZGIiwibmJmIjoxNTc1OTQ4NzkwLCJleHAiOjE1NzY1NTM1OTAsImlhdCI6MTU3NTk0ODc5MH0.5SAMtF9jogQU9lP37NrqDpwMbTyIr803Gwxh13HOCvQ
Content-Type: application/json

{
  "name": "test 123"
}


### DELETE: Remove TicketCategory by id (/api/ticketcategories/{id})
DELETE http://localhost:5000/api/ticketcategories/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjMwIiwicm9sZSI6IlNUQUZGIiwibmJmIjoxNTc1OTQ4NzkwLCJleHAiOjE1NzY1NTM1OTAsImlhdCI6MTU3NTk0ODc5MH0.5SAMtF9jogQU9lP37NrqDpwMbTyIr803Gwxh13HOCvQ