GET http://localhost:5000/api/users HTTP/1.1
###
GET http://localhost:5000/api/users/1 HTTP/1.1

###
PUT http://localhost:5000/api/users/1 HTTP/1.1
Content-Type: application/json

{
    "email": "admin1@admin.com"
}

### Create new user
POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjEiLCJyb2xlIjoiQURNSU4iLCJuYmYiOjE1NzI5OTk2NDksImV4cCI6MTU3MzYwNDQ0OSwiaWF0IjoxNTcyOTk5NjQ5fQ.BqMHb6QYH69iyYU4TGQ0iZKVHSzf1Y_uLt6GHiOI0bY

{
    "fullname": "Ninh",
    "email": "ninh2@ninh.com",
    "identifier": "02039291",
    "password": "12345678"
}
### Login
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "ninh2@ninh.com",
    "password": "12345678"
}
### 
POST http://localhost:5000/api/auth/me HTTP/1.1
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "$2b$10$IZshIpJy3mRvjTGJJYD45OOccUcUNI8RrCUvURHcemPbdNfXR/q3i"
}

###
GET http://localhost:5000/api/users/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjMiLCJyb2xlIjoiU1RBRkYiLCJuYmYiOjE1NzI5OTk2OTIsImV4cCI6MTU3MzYwNDQ5MiwiaWF0IjoxNTcyOTk5NjkyfQ.oiyoTvslYMA-9E66TL913c6EHf0lBb-bGan64P8r02w

### get airports
GET http://localhost:5000/api/airports?page=3 HTTP/1.1
Content-Type: application/json
